export type Env = {
  NEXTAUTH_URL?: string;
  NEXTAUTH_SECRET?: string;
  APP_URL?: string;
  APP_BRAND_NAME: string;
  DEFAULT_TIMEZONE: string;
  DATABASE_URL?: string;
  REDIS_URL?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GOOGLE_PROJECT_ID?: string;
  GOOGLE_PUBSUB_TOPIC?: string;
  GOOGLE_PUBSUB_VERIFICATION_TOKEN?: string;
  GOOGLE_OAUTH_SCOPES?: string;
  MICROSOFT_CLIENT_ID?: string;
  MICROSOFT_CLIENT_SECRET?: string;
  MICROSOFT_TENANT_ID: string;
  MICROSOFT_OAUTH_SCOPES?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  STRIPE_PRICE_PRO_MONTH?: string;
  SENTRY_DSN?: string;
  POSTHOG_API_KEY?: string;
  POSTHOG_HOST?: string;
  OPENAI_API_KEY?: string;
  OPENAI_BASE_URL?: string;
  KMS_PROVIDER?: 'gcp'|'aws'|'azure';
  KMS_KEY_ID?: string;
  ENCRYPTION_CACHE_TTL_SECONDS: number;
  EPHEMERAL_STORAGE_MODE: boolean;
  RETENTION_DAYS: number;
};

export function getEnv(): Env {
  const env = process.env;
  return {
    NEXTAUTH_URL: env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: env.NEXTAUTH_SECRET,
    APP_URL: env.APP_URL,
    APP_BRAND_NAME: env.APP_BRAND_NAME ?? 'Rivor',
    DEFAULT_TIMEZONE: env.DEFAULT_TIMEZONE ?? 'America/New_York',
    DATABASE_URL: env.DATABASE_URL,
    REDIS_URL: env.REDIS_URL,
    GOOGLE_CLIENT_ID: env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: env.GOOGLE_CLIENT_SECRET,
    GOOGLE_PROJECT_ID: env.GOOGLE_PROJECT_ID,
    GOOGLE_PUBSUB_TOPIC: env.GOOGLE_PUBSUB_TOPIC,
    GOOGLE_PUBSUB_VERIFICATION_TOKEN: env.GOOGLE_PUBSUB_VERIFICATION_TOKEN,
    GOOGLE_OAUTH_SCOPES: env.GOOGLE_OAUTH_SCOPES,
    MICROSOFT_CLIENT_ID: env.MICROSOFT_CLIENT_ID,
    MICROSOFT_CLIENT_SECRET: env.MICROSOFT_CLIENT_SECRET,
    MICROSOFT_TENANT_ID: env.MICROSOFT_TENANT_ID ?? 'common',
    MICROSOFT_OAUTH_SCOPES: env.MICROSOFT_OAUTH_SCOPES,
    STRIPE_SECRET_KEY: env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: env.STRIPE_WEBHOOK_SECRET,
    STRIPE_PRICE_PRO_MONTH: env.STRIPE_PRICE_PRO_MONTH,
    SENTRY_DSN: env.SENTRY_DSN,
    POSTHOG_API_KEY: env.POSTHOG_API_KEY,
    POSTHOG_HOST: env.POSTHOG_HOST,
    OPENAI_API_KEY: env.OPENAI_API_KEY,
    OPENAI_BASE_URL: env.OPENAI_BASE_URL,
    KMS_PROVIDER: env.KMS_PROVIDER as Env['KMS_PROVIDER'],
    KMS_KEY_ID: env.KMS_KEY_ID,
    ENCRYPTION_CACHE_TTL_SECONDS: Number(env.ENCRYPTION_CACHE_TTL_SECONDS ?? 60),
    EPHEMERAL_STORAGE_MODE: String(env.EPHEMERAL_STORAGE_MODE ?? 'false') === 'true',
    RETENTION_DAYS: Number(env.RETENTION_DAYS ?? 90),
  };
}


